version: "3"
services:
  kgwapi:
    build: ./server
    environment:
      - KUBECONFIG=/kube/config
      - ANALYTICS_ENABLED=false
    volumes:
      - $HOME/.kube/config:/kube/config:ro
    ports:
      - 8080:8080
