---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kgwtest
  name: kgwtest
  namespace: kusk-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kgwtest
  template:
    metadata:
      labels:
        app: kgwtest
    spec:
      containers:
        - image: jasmingacic/kuskgateway-api:latest
          imagePullPolicy: Always
          name: kuskgateway-api
      serviceAccountName: kusk-gateway-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kgwtest
  name: kgwtest
  namespace: kusk-system
spec:
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: kgwtest
