---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kgwtest
  name: kgwtest
  namespace: kusk-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kgwtest
  template:
    metadata:
      labels:
        app: kgwtest
    spec:
      containers:
        - image: kubeshop/kusk-gateway-api:latest
          imagePullPolicy: IfNotPresent
          name: kusk-gateway-api
        - image: kubeshop/kusk-gateway-api-websocket:latest
          imagePullPolicy: IfNotPresent
          args:
            - --port=8081
          name: kusk-gateway-api-websocket

      serviceAccountName: kusk-gateway-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kgwtest
  name: kgwtest
  namespace: kusk-system
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
    - port: 8081
      name: websocket
      targetPort: 8081
  type: LoadBalancer
  selector:
    app: kgwtest
