/*
 * Kusk Gateway API
 *
 * This is the Kusk Gateway Management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// CreateNewStaticRouteApiService is a service that implements the logic for the CreateNewStaticRouteApiServicer
// This service should implement the business logic for every endpoint for the CreateNewStaticRouteApi API.
// Include any external packages or services that will be required by this service.
type CreateNewStaticRouteApiService struct {
}

// NewCreateNewStaticRouteApiService creates a default api service
func NewCreateNewStaticRouteApiService() CreateNewStaticRouteApiServicer {
	return &CreateNewStaticRouteApiService{}
}

// CreateStaticRoute - create new static route
func (s *CreateNewStaticRouteApiService) CreateStaticRoute(ctx context.Context, staticRouteItem StaticRouteItem) (ImplResponse, error) {
	// TODO - update CreateStaticRoute with the required logic for this service method.
	// Add api_create_new_static_route_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, StaticRouteItem{}) or use other options such as http.Ok ...
	//return Response(200, StaticRouteItem{}), nil

	//TODO: Uncomment the next line to return response Response(400, string{}) or use other options such as http.Ok ...
	//return Response(400, string{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateStaticRoute method not implemented")
}
