/*
 * Kusk Gateway API
 *
 * This is the Kusk Gateway Management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// ApisApiService is a service that implements the logic for the ApisApiServicer
// This service should implement the business logic for every endpoint for the ApisApi API.
// Include any external packages or services that will be required by this service.
type ApisApiService struct {
}

// NewApisApiService creates a default api service
func NewApisApiService() ApisApiServicer {
	return &ApisApiService{}
}

// GetApis - Get a list of APIs
func (s *ApisApiService) GetApis(ctx context.Context, fleet string) (ImplResponse, error) {
	// TODO - update GetApis with the required logic for this service method.
	// Add api_apis_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []ApiItem{}) or use other options such as http.Ok ...
	//return Response(200, []ApiItem{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetApis method not implemented")
}

// GetPostProcessedOpenApiSpec - Get the post-processed OpenAPI spec by API id
func (s *ApisApiService) GetPostProcessedOpenApiSpec(ctx context.Context, apiId string) (ImplResponse, error) {
	// TODO - update GetPostProcessedOpenApiSpec with the required logic for this service method.
	// Add api_apis_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(200, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetPostProcessedOpenApiSpec method not implemented")
}

// GetRawOpenApiSpec - Get the raw OpenAPI spec by API id
func (s *ApisApiService) GetRawOpenApiSpec(ctx context.Context, apiId string) (ImplResponse, error) {
	// TODO - update GetRawOpenApiSpec with the required logic for this service method.
	// Add api_apis_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, map[string]interface{}{}) or use other options such as http.Ok ...
	//return Response(200, map[string]interface{}{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetRawOpenApiSpec method not implemented")
}
