/*
 * Kusk Gateway API
 *
 * This is the Kusk Gateway Management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// FleetsApiService is a service that implements the logic for the FleetsApiServicer
// This service should implement the business logic for every endpoint for the FleetsApi API.
// Include any external packages or services that will be required by this service.
type FleetsApiService struct {
}

// NewFleetsApiService creates a default api service
func NewFleetsApiService() FleetsApiServicer {
	return &FleetsApiService{}
}

// GetEnvoyFleet - Get details for a single envoy fleet
func (s *FleetsApiService) GetEnvoyFleet(ctx context.Context, namespace string, name string) (ImplResponse, error) {
	// TODO - update GetEnvoyFleet with the required logic for this service method.
	// Add api_fleets_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, EnvoyFleetItem{}) or use other options such as http.Ok ...
	//return Response(200, EnvoyFleetItem{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetEnvoyFleet method not implemented")
}

// GetEnvoyFleets - Get a list of envoy fleets
func (s *FleetsApiService) GetEnvoyFleets(ctx context.Context, namespace string) (ImplResponse, error) {
	// TODO - update GetEnvoyFleets with the required logic for this service method.
	// Add api_fleets_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []EnvoyFleetItem{}) or use other options such as http.Ok ...
	//return Response(200, []EnvoyFleetItem{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetEnvoyFleets method not implemented")
}
