/*
 * Kusk Gateway API
 *
 * This is the Kusk Gateway Management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// NamespacesApiService is a service that implements the logic for the NamespacesApiServicer
// This service should implement the business logic for every endpoint for the NamespacesApi API.
// Include any external packages or services that will be required by this service.
type NamespacesApiService struct {
}

// NewNamespacesApiService creates a default api service
func NewNamespacesApiService() NamespacesApiServicer {
	return &NamespacesApiService{}
}

// GetNamespaces - Get a list of namespaces
func (s *NamespacesApiService) GetNamespaces(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetNamespaces with the required logic for this service method.
	// Add api_namespaces_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []NamespaceItem{}) or use other options such as http.Ok ...
	//return Response(200, []NamespaceItem{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetNamespaces method not implemented")
}
