/*
 * Kusk Gateway API
 *
 * This is the Kusk Gateway Management API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ServiceItem struct {
	Name string `json:"name"`

	Status string `json:"status"`

	Namespace string `json:"namespace"`
}

// AssertServiceItemRequired checks if the required fields are not zero-ed
func AssertServiceItemRequired(obj ServiceItem) error {
	elements := map[string]interface{}{
		"name":      obj.Name,
		"status":    obj.Status,
		"namespace": obj.Namespace,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseServiceItemRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ServiceItem (e.g. [][]ServiceItem), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseServiceItemRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aServiceItem, ok := obj.(ServiceItem)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertServiceItemRequired(aServiceItem)
	})
}
