name: build and test

# Cancel any pending or running workflow if the new one is triggered
concurrency:
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: make build
