name: build

concurrency:
  group: build
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: make build
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
