name: build

concurrency:
  group: build
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push api-server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/api-server/Dockerfile
          platforms: linux/amd64,linux/arm64

      - name: Build and push websocket
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/websocket/Dockerfile
          platforms: linux/amd64,linux/arm64

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
