name: Release Kusk Gateway

# Cancel any pending or running workflow if the new one is triggered
concurrency:
  group: "release"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

on:
  push:
    tags: 
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:

  release:
    name: Create and upload release-artifacts
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      changed_resources: ${{ steps.check_modified_resources.outputs.changed_resources }}
      release_version: ${{ steps.check_modified_resources.outputs.release_version }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker metadata for Kusk Gateway API
        id: meta-kusk-gateway-api
        uses: docker/metadata-action@v3
        with:
          images: kubeshop/kusk-gateway-api
          tags: |
            type=match,pattern=v(.*)
            type=sha
          flavor: |
            latest=true
      -
        name: Build and push Kusk Gateway API
        uses: docker/build-push-action@v2
        with:
          context: .
          file: server/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-kusk-gateway-api.outputs.tags }}
          labels: ${{ steps.meta-kusk-gateway-api.outputs.labels }}
      -
        name: Run GoReleaser to publish release notes
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --skip-sign
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT_TOKEN }}



